routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use News\Http\Controllers\CategoryController;
use News\Http\Controllers\NewsController;
use News\Http\Controllers\SettingsController;
use News\Models\Settings;



Route::middleware('web')->group(function (){
    Route::middleware('auth_pacage')->group(function () {
        Route::group(['prefix'=>"admin", 'as'=>'admin.', 'middleware' => 'is_admin'],static function(){
            Route::resource('news', NewsController::class);
            Route::get('news/lock/{news}',[NewsController::class,'lock'])->name('lock');
            Route::get('news/unlock/{news}',[NewsController::class,'unlock'])->name('unlock');
            Route::group(['prefix' => 'news', 'as' => 'news.'], static function(){
                Route::post('remove_image/{news}',[NewsController::class,'removeImage']);
                Route::resource('category', CategoryController::class);
                Route::resource('settings', SettingsController::class);
            });
        });
    });
    try {
        $settings = Settings::find(1);
        Route::get('/'.$settings->url,[NewsController::class,'frontIndex'])->name('news');
        Route::get('/'.$settings->url.'/category/{url}',[NewsController::class,'frontCategory'])->name('news.category');
        Route::get('/'.$settings->url . '/{url}',[NewsController::class,'news'])->name('news.news');
    } catch (Exception $exception) {
        //throw $th;
    }
});

resources/views/news/category.blade.php
@extends('layouts.admin')
@section('title',config('news_module.title'))
@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <x-admin.navigation :links="$links" />
                <x-news::category />
            </div>
        </div>
    </div>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.news.index")}}">{{ config('news_module.title') }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Категории</li>
        </ol>
    </div>
@endsection

resources/views/news/create.blade.php
@extends('layouts.admin')
@section('title',config('news_module.title'))
@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <x-admin.navigation :links="$links" />
                <x-news::create :links="$linksContent" />
            </div>
        </div>
    </div>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.news.index")}}">{{ config('news_module.title') }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Создание</li>
        </ol>
    </div>
@endsection

resources/views/news/edit.blade.php
@extends('layouts.admin')
@section('title',config('news_module.title'))
@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <x-admin.navigation :links="$links" />
                <x-news::edit :links="$linksContent" :news="$news" />
            </div>
        </div>
    </div>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.news.index")}}">{{ config('news_module.title') }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Редактирование</li>
        </ol>
    </div>
@endsection

resources/views/news/front/category.blade.php
@extends('layouts.inner')
@section('title', $title)
@section('description', $title)
@section('page', true)
@section('content')
    <div class="content">
        @php
            $breadcrumbs = [...config('news_module.routes'), ['title' => $title]];
        @endphp

        <div class="innerPage-header header_bredcrambs">
            <x-front.breadcrumbs :breadcrumbs="$breadcrumbs" flag='true' />
            <div class="container">
                <h1 class="wow fadeIn">{{ $title }}</h1>
            </div>
        </div>

        <x-news::front.category :news="$news" :settings="$settings" />
    </div>

@endsection

resources/views/news/front/index.blade.php
@extends('layouts.inner')
@section('title',$settings->seoTitle ?? $settings->title)
@section('description',$settings->seoDescription)
@section('keywords',$settings->seoKeywords)
@section('page',true)
@section('content')
<div class="content">
    {{-- <x-front.breadcrumbs :breadcrumbs="$breadcrumbs" /> --}}
    {{-- <h2>{{ $title }}</h2> --}}

    <x-news::front.category :news="$news" :settings="$settings"/>
</div>

@endsection

resources/views/news/front/news.blade.php
{{-- @dd($news) --}}
@extends('layouts.inner')
@section('title',$news->seoTitle)
@section('description',$news->seoDescription)
@section('keywords',$news->seoKeywords)
@section('page',true)
@section('content')
<div class="content">

    <x-news::front.item :news="$news" />
</div>

@endsection

resources/views/news/index.blade.php
@extends('layouts.admin')
@section('title',config('news_module.title'))
@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <x-admin.navigation :links="$links" />
                <x-news::news />
            </div>
        </div>
    </div>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.news.index")}}">{{config('news_module.title')}}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Список</li>
        </ol>
    </div>
@endsection

resources/views/news/settings.blade.php
@extends('layouts.admin')
@section('title',config('news_module.title'))
@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <x-admin.navigation :links="$links" />
                <x-news::settings />
            </div>
        </div>
    </div>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.news.index")}}">{{ config('news_module.title') }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Настройки</li>
        </ol>
    </div>
@endsection